# This workflow will build a Nimble project

name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
      
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # ⚠️ This setups the latest stable Nim version
    - name: Install Nim
      uses: iffy/install-nim@v5
    - name: Install dependencies
      run: nimble install -y
    - name: Build
      run: nimble build --define:release --out:lucem
    - name: Compress
      run: tar -czvf lucem-amd64.tar.gz ./lucem

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build
        path: lucem
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./lucem
        asset_name: lucem-amd64.tar.gz
        asset_content_type: application/gzip
